AllCops:
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rake'
    - '**/*.rb'
    - '**/*.gemspec'
  Exclude:
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
  DisplayCopNames: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Layout/EmptyLines:
  Exclude:
    - '**/Gemfile'

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/Gemfile'

Naming/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Guardfile'

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  AllowInnerSlashes: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 240

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 6

Gemspec/RequiredRubyVersion:
  Enabled: false
