version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update rubygems
          command: gem update --system

      - run:
          name: Update Bunndler
          command: gem update bundler

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "image_flux.gemspec" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
            bundle update

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "image_flux.gemspec" }}

      - run:
          name: RSpec
          command: |
            mkdir /tmp/test-results

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress

      - run:
          name: Rubocop
          command: bundle exec rubocop

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
